/*
 * Copyright (C) 2013 Max Planck Institute for Psycholinguistics
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package nl.mpi.yaas.common.db;

/**
 * Created on : Feb 11, 2013, 8:21:16 PM
 *
 * @author Peter Withers <peter.withers@mpi.nl>
 */
public class TestData {

    static final public String[] testData = new String[]{
        "<DataNode Label=\"Sign Language Typology\" ID=\"hdl:1839/00-0000-0000-0001-2A9A-4\">"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"Sign Language Typology\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"Sign Language Typology\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + " <Type Name=\"Subnode\" ID=\"subnode\" Format=\"imdi\"/>"
        + "</DataNode>",
        "<DataNode Label=\"Sign Language Typology\" ID=\"hdl:1839/00-0000-0000-0001-2A9A-4\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2A9B-9</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"Sign Language Typology\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"Sign Language Typology\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<Type Name=\"Session\" ID=\"imdi.session\" Format=\"imdi\"/>"
        + "</DataNode>",
        "<DataNode Label=\"Sign Language Typology\" ID=\"hdl:1839/00-0000-0000-0001-2A9A-4\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2A9B-9</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AB4-0</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"Sign Language Typology\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"Sign Language Typology\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"Sign Language Typology\" ID=\"hdl:1839/00-0000-0000-0001-2A9A-4\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2A9B-9</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AB4-0</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2FA3-5</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"Sign Language Typology\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"Sign Language Typology\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<Type Name=\"Session\" ID=\"imdi.session\" Format=\"imdi\"/>"
        + "</DataNode>",
        "<DataNode Label=\"Sign Language Typology\" ID=\"hdl:1839/00-0000-0000-0001-2A9A-4\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2A9B-9</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AB4-0</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2FA3-5</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2FEE-D</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"Sign Language Typology\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"Sign Language Typology\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + " <Type Name=\"Subnode\" ID=\"subnode\" Format=\"imdi\"/>"
        + "</DataNode>",
        "<DataNode Label=\"contact signing\" ID=\"hdl:1839/00-0000-0000-0001-2A9B-9\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AB1-4</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"contact signing\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"contact signing\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"contact signing\" ID=\"hdl:1839/00-0000-0000-0001-2A9B-9\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AB1-4</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AAE-4</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"contact signing\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"contact signing\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + " <Type Name=\"Subnode\" ID=\"subnode\" Format=\"imdi\"/>"
        + "</DataNode>",
        "<DataNode Label=\"contact signing\" ID=\"hdl:1839/00-0000-0000-0001-2A9B-9\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AB1-4</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AAE-4</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-000D-B73A-D</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"contact signing\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"contact signing\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<Type Name=\"Session\" ID=\"imdi.session\" Format=\"imdi\"/>"
        + "</DataNode>",
        "<DataNode Label=\"contact signing\" ID=\"hdl:1839/00-0000-0000-0001-2A9B-9\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AB1-4</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AAE-4</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-000D-B73A-D</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AAB-5</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"contact signing\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"contact signing\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + " <Type Name=\"Subnode\" ID=\"subnode\" Format=\"imdi\"/>"
        + "</DataNode>",
        "<DataNode Label=\"contact signing\" ID=\"hdl:1839/00-0000-0000-0001-2A9B-9\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AB1-4</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AAE-4</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-000D-B73A-D</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AAB-5</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AA8-4</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"contact signing\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"contact signing\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"contact signing\" ID=\"hdl:1839/00-0000-0000-0001-2A9B-9\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AB1-4</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AAE-4</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-000D-B73A-D</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AAB-5</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AA8-4</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AA2-6</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"contact signing\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"contact signing\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"contact signing\" ID=\"hdl:1839/00-0000-0000-0001-2A9B-9\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AB1-4</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AAE-4</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-000D-B73A-D</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AAB-5</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AA8-4</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AA2-6</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2A9C-7</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"contact signing\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"contact signing\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"contact signing\" ID=\"hdl:1839/00-0000-0000-0001-2A9B-9\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AB1-4</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AAE-4</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-000D-B73A-D</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AAB-5</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AA8-4</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AA2-6</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2A9C-7</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AA5-5</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"contact signing\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"contact signing\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"contact signing\" ID=\"hdl:1839/00-0000-0000-0001-2A9B-9\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AB1-4</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AAE-4</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-000D-B73A-D</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AAB-5</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AA8-4</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AA2-6</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2A9C-7</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AA5-5</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2A9F-4</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"contact signing\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"contact signing\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"CS_ChinTurk1\" ID=\"hdl:1839/00-0000-0000-0001-2AB1-4\">"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.Description\" FieldValue=\"Chinese signer (F, age 32, Ph.D. student in USA) and Turkish signer (M, age 22) first contact. Speakers were given suggested topics to discuss of the general introductory variety.\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Actors.Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.MDGroup.Actors.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Location.Country\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.MDGroup.Location.Country\" FieldValue=\"Unspecified\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Location.Continent\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.MDGroup.Location.Continent\" FieldValue=\"Asia\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.Name\" FieldValue=\"CS_ChinTurk1\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"References.Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.References.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.Title\" FieldValue=\"Contact Signing Chinese-Turkish 1st contact\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Date\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.Date\" FieldValue=\"2004-02-02\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Location.Address\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.MDGroup.Location.Address\" FieldValue=\"Unspecified\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"CS_ChinTurk1\" ID=\"hdl:1839/00-0000-0000-0001-2AB1-4\">"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.Description\" FieldValue=\"Chinese signer (F, age 32, Ph.D. student in USA) and Turkish signer (M, age 22) first contact. Speakers were given suggested topics to discuss of the general introductory variety.\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Actors.Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.MDGroup.Actors.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Location.Country\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.MDGroup.Location.Country\" FieldValue=\"Unspecified\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Location.Continent\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.MDGroup.Location.Continent\" FieldValue=\"Asia\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.Name\" FieldValue=\"CS_ChinTurk1\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"References.Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.References.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.Title\" FieldValue=\"Contact Signing Chinese-Turkish 1st contact\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Date\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.Date\" FieldValue=\"2004-02-02\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Location.Address\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.MDGroup.Location.Address\" FieldValue=\"Unspecified\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"CS_ChinTurk1\" ID=\"hdl:1839/00-0000-0000-0001-2AB1-4\">"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.Description\" FieldValue=\"Chinese signer (F, age 32, Ph.D. student in USA) and Turkish signer (M, age 22) first contact. Speakers were given suggested topics to discuss of the general introductory variety.\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Actors.Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.MDGroup.Actors.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Location.Country\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.MDGroup.Location.Country\" FieldValue=\"Unspecified\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Location.Continent\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.MDGroup.Location.Continent\" FieldValue=\"Asia\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.Name\" FieldValue=\"CS_ChinTurk1\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"References.Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.References.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.Title\" FieldValue=\"Contact Signing Chinese-Turkish 1st contact\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Date\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.Date\" FieldValue=\"2004-02-02\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Location.Address\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.MDGroup.Location.Address\" FieldValue=\"Unspecified\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"CS_ChinTurk1\" ID=\"hdl:1839/00-0000-0000-0001-2AB1-4\">"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.Description\" FieldValue=\"Chinese signer (F, age 32, Ph.D. student in USA) and Turkish signer (M, age 22) first contact. Speakers were given suggested topics to discuss of the general introductory variety.\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Actors.Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.MDGroup.Actors.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Location.Country\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.MDGroup.Location.Country\" FieldValue=\"Unspecified\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Location.Continent\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.MDGroup.Location.Continent\" FieldValue=\"Asia\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.Name\" FieldValue=\"CS_ChinTurk1\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"References.Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.References.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.Title\" FieldValue=\"Contact Signing Chinese-Turkish 1st contact\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Date\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.Date\" FieldValue=\"2004-02-02\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Location.Address\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.MDGroup.Location.Address\" FieldValue=\"Unspecified\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"CS_ChinTurk1\" ID=\"hdl:1839/00-0000-0000-0001-2AB1-4\">"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.Description\" FieldValue=\"Chinese signer (F, age 32, Ph.D. student in USA) and Turkish signer (M, age 22) first contact. Speakers were given suggested topics to discuss of the general introductory variety.\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Actors.Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.MDGroup.Actors.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Location.Country\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.MDGroup.Location.Country\" FieldValue=\"Unspecified\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Location.Continent\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.MDGroup.Location.Continent\" FieldValue=\"Asia\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.Name\" FieldValue=\"CS_ChinTurk1\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"References.Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.References.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.Title\" FieldValue=\"Contact Signing Chinese-Turkish 1st contact\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Date\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.Date\" FieldValue=\"2004-02-02\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Location.Address\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.MDGroup.Location.Address\" FieldValue=\"Unspecified\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"CS_ChinTurk1\" ID=\"hdl:1839/00-0000-0000-0001-2AB1-4\">"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.Description\" FieldValue=\"Chinese signer (F, age 32, Ph.D. student in USA) and Turkish signer (M, age 22) first contact. Speakers were given suggested topics to discuss of the general introductory variety.\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Actors.Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.MDGroup.Actors.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Location.Country\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.MDGroup.Location.Country\" FieldValue=\"Unspecified\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Location.Continent\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.MDGroup.Location.Continent\" FieldValue=\"Asia\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.Name\" FieldValue=\"CS_ChinTurk1\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"References.Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.References.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.Title\" FieldValue=\"Contact Signing Chinese-Turkish 1st contact\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Date\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.Date\" FieldValue=\"2004-02-02\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Location.Address\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.MDGroup.Location.Address\" FieldValue=\"Unspecified\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"Sign Language Typology\" ID=\"hdl:1839/00-0000-0000-0001-2A9A-4\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2FA3-5</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"Sign Language Typology\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"Sign Language Typology\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"Sign Language Typology\" ID=\"hdl:1839/00-0000-0000-0001-2A9A-4\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2FA3-5</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AB4-0</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"Sign Language Typology\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"Sign Language Typology\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"Sign Language Typology\" ID=\"hdl:1839/00-0000-0000-0001-2A9A-4\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2FA3-5</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AB4-0</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2FEE-D</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"Sign Language Typology\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"Sign Language Typology\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"Sign Language Typology\" ID=\"hdl:1839/00-0000-0000-0001-2A9A-4\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2FA3-5</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AB4-0</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2FEE-D</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2A9B-9</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"Sign Language Typology\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"Sign Language Typology\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"village sign languages\" ID=\"hdl:1839/00-0000-0000-0001-2FA3-5\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2FA4-B</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"village sign languages\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"village sign languages\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"Bali\" ID=\"hdl:1839/00-0000-0000-0001-2FA4-B\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0008-CAD1-B</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"Bali\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"Kata Kolok\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"Bali\" ID=\"hdl:1839/00-0000-0000-0001-2FA4-B\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0008-CAD1-B</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0008-C805-D</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"Bali\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"Kata Kolok\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"Vos\" ID=\"hdl:1839/00-0000-0000-0008-CAD1-B\">"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"Vos\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"Vos\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"Marsaja\" ID=\"hdl:1839/00-0000-0000-0008-C805-D\">"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"Marsaja\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"Marsaja\" ID=\"hdl:1839/00-0000-0000-0008-C805-D\">"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"Marsaja\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"urban sign languages\" ID=\"hdl:1839/00-0000-0000-0001-2AB4-0\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2C2D-F</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"urban sign languages\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"urban sign languages\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"urban sign languages\" ID=\"hdl:1839/00-0000-0000-0001-2AB4-0\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2C2D-F</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2E76-0</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"urban sign languages\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"urban sign languages\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"urban sign languages\" ID=\"hdl:1839/00-0000-0000-0001-2AB4-0\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2C2D-F</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2E76-0</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2C32-7</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"urban sign languages\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"urban sign languages\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"urban sign languages\" ID=\"hdl:1839/00-0000-0000-0001-2AB4-0\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2C2D-F</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2E76-0</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2C32-7</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2DA9-A</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"urban sign languages\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"urban sign languages\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"urban sign languages\" ID=\"hdl:1839/00-0000-0000-0001-2AB4-0\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2C2D-F</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2E76-0</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2C32-7</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2DA9-A</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AB5-D</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"urban sign languages\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"urban sign languages\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"urban sign languages\" ID=\"hdl:1839/00-0000-0000-0001-2AB4-0\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2C2D-F</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2E76-0</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2C32-7</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2DA9-A</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AB5-D</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0004-D511-0</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"urban sign languages\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"urban sign languages\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"urban sign languages\" ID=\"hdl:1839/00-0000-0000-0001-2AB4-0\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2C2D-F</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2E76-0</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2C32-7</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2DA9-A</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AB5-D</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0004-D511-0</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2CB9-5</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"urban sign languages\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"urban sign languages\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"urban sign languages\" ID=\"hdl:1839/00-0000-0000-0001-2AB4-0\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2C2D-F</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2E76-0</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2C32-7</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2DA9-A</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AB5-D</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0004-D511-0</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2CB9-5</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2ED0-D</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"urban sign languages\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"urban sign languages\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"urban sign languages\" ID=\"hdl:1839/00-0000-0000-0001-2AB4-0\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2C2D-F</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2E76-0</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2C32-7</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2DA9-A</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AB5-D</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0004-D511-0</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2CB9-5</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2ED0-D</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2C7B-0</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"urban sign languages\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"urban sign languages\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"urban sign languages\" ID=\"hdl:1839/00-0000-0000-0001-2AB4-0\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2C2D-F</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2E76-0</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2C32-7</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2DA9-A</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AB5-D</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0004-D511-0</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2CB9-5</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2ED0-D</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2C7B-0</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2D8B-3</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"urban sign languages\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"urban sign languages\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"Germany\" ID=\"hdl:1839/00-0000-0000-0001-2C2D-F\">"
        + "<ChildIds>hdl:1839/00-0000-0000-000D-B73D-9</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"Germany\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"Germany\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"Germany\" ID=\"hdl:1839/00-0000-0000-0001-2C2D-F\">"
        + "<ChildIds>hdl:1839/00-0000-0000-000D-B73D-9</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2C2E-1</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"Germany\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"Germany\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"Germany Catalogue\" ID=\"hdl:1839/00-0000-0000-000D-B73D-9\">"
        + "<FieldGroup Label=\"Keys.Key.CorpusTreePath\">"
        + "<FieldData KeyName=\"CorpusTreePath\" Path=\".METATRANSCRIPT.Catalogue.Keys.Key(4)\" FieldValue=\"MPI corpora: Sign Language Typology: urban sign languages: Germany\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Quality\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Quality\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Format.Text\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Format.Text\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Project.Contact.Address\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Project.Contact.Address\" FieldValue=\"Centre for Sign Linguistics and Deaf Studies\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Date\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Date\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"ContactPerson\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.ContactPerson\" FieldValue=\"Gladys Tang\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Pricing\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Pricing\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Format.Image\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Format.Image\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Name\" FieldValue=\"Germany Catalogue\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Title\" FieldValue=\"Germany\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Access.Publisher\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Access.Publisher\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Project.Contact.Email\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Project.Contact.Email\" FieldValue=\"gtang@arts.cuhk.edu.hk\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Format.Video\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Format.Video\" FieldValue=\"video/x-mpeg1, video/x-mpeg2\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"ContentType\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.ContentType\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Project.Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Project.Name\" FieldValue=\"SL TYpology -urban - DGS\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Project.Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Project.Title\" FieldValue=\"Sign Language Typology\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"DistributionForm\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.DistributionForm\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Applications\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Applications\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Format.Audio\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Format.Audio\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Access.Date\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Access.Date\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Author\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Author\" FieldValue=\"Gladys Tang\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Project.Contact.Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Project.Contact.Name\" FieldValue=\"Gladys Tang\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Keys.Key.CorpusBrowserLink\">"
        + "<FieldData KeyName=\"CorpusBrowserLink\" Path=\".METATRANSCRIPT.Catalogue.Keys.Key(2)\" FieldValue=\"http://corpus1.mpi.nl/ds/imdi_browser/?openpath=MPI76845%23\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Access.Owner\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Access.Owner\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Publisher\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Publisher\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Id\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Id\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Size\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Size\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Access.Contact\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Access.Contact\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Access.Availability\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Access.Availability\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Project.Contact.Organisation\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Project.Contact.Organisation\" FieldValue=\"The Chinese University of Hong Kong\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Keys.Key.CorpusImdiLink\">"
        + "<FieldData KeyName=\"CorpusImdiLink\" Path=\".METATRANSCRIPT.Catalogue.Keys.Key\" FieldValue=\"http://corpus1.mpi.nl/qfs1/media-archive/silang_data/Corpusstructure/1-02-02.imdi\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"SmallestAnnotationUnit\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.SmallestAnnotationUnit\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Keys.Key.CorpusArchiveHandle\">"
        + "<FieldData KeyName=\"CorpusArchiveHandle\" Path=\".METATRANSCRIPT.Catalogue.Keys.Key(3)\" FieldValue=\"hdl:1839/00-0000-0000-0001-2C2D-F\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Project.Id\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Project.Id\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"Sign Language Typology\" ID=\"hdl:1839/00-0000-0000-0001-2A9A-4\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2A9B-9</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AB4-0</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2FEE-D</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2FA3-5</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"Sign Language Typology\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"Sign Language Typology\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"contact signing\" ID=\"hdl:1839/00-0000-0000-0001-2A9B-9\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AA2-6</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-000D-B73A-D</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2A9C-7</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AB1-4</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2A9F-4</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AAE-4</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AA5-5</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AAB-5</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AA8-4</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"contact signing\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"contact signing\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"1_contact_S-K\" ID=\"hdl:1839/00-0000-0000-0001-2AA2-6\">"
        + "<FieldGroup Label=\"Date\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.Date\" FieldValue=\"2004-06-23\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.Name\" FieldValue=\"1_contact_S-K\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Location.Continent\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.MDGroup.Location.Continent\" FieldValue=\"Unspecified\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Actors.Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.MDGroup.Actors.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Location.Country\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.MDGroup.Location.Country\" FieldValue=\"Unspecified\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.Title\" FieldValue=\"First contact S-K\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Location.Address\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.MDGroup.Location.Address\" FieldValue=\"Unspecified\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Session.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"Sign Language Typology\" ID=\"hdl:1839/00-0000-0000-0001-2A9A-4\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AB4-0</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2A9B-9</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2FEE-D</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2FA3-5</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"Sign Language Typology\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"Sign Language Typology\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"urban sign languages\" ID=\"hdl:1839/00-0000-0000-0001-2AB4-0\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0004-D511-0</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2CB9-5</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2C2D-F</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2ED0-D</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2DA9-A</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2D8B-3</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2E76-0</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AB5-D</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2C7B-0</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2C32-7</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"urban sign languages\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"urban sign languages\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"Jordan\" ID=\"hdl:1839/00-0000-0000-0004-D511-0\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0004-D512-F</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-000D-B745-4</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"Jordan\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"Jordan\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"Texts\" ID=\"hdl:1839/00-0000-0000-0004-D512-F\">"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"Texts\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"Texts\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"Sign Language Typology\" ID=\"hdl:1839/00-0000-0000-0001-2A9A-4\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AB4-0</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2FA3-5</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2FEE-D</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2A9B-9</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"Sign Language Typology\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"Sign Language Typology\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"urban sign languages\" ID=\"hdl:1839/00-0000-0000-0001-2AB4-0\">"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2E76-0</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2CB9-5</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2AB5-D</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0004-D511-0</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2C32-7</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2C7B-0</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2ED0-D</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2DA9-A</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2D8B-3</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2C2D-F</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"urban sign languages\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"urban sign languages\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"Brazil\" ID=\"hdl:1839/00-0000-0000-0001-2E76-0\">"
        + "<ChildIds>hdl:1839/00-0000-0000-000D-B743-0</ChildIds>"
        + "<ChildIds>hdl:1839/00-0000-0000-0001-2E77-E</ChildIds>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"Brazil\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"Brazil\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"Brazil Catalogue\" ID=\"hdl:1839/00-0000-0000-000D-B743-0\">"
        + "<FieldGroup Label=\"Size\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Size\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Keys.Key.CorpusArchiveHandle\">"
        + "<FieldData KeyName=\"CorpusArchiveHandle\" Path=\".METATRANSCRIPT.Catalogue.Keys.Key(3)\" FieldValue=\"hdl:1839/00-0000-0000-0001-2E76-0\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Quality\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Quality\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Id\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Id\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Applications\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Applications\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"SmallestAnnotationUnit\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.SmallestAnnotationUnit\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Format.Audio\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Format.Audio\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Name\" FieldValue=\"Brazil Catalogue\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Project.Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Project.Title\" FieldValue=\"Sign Language Typology - urban sign languages - Brazil\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Access.Owner\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Access.Owner\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Access.Publisher\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Access.Publisher\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"DistributionForm\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.DistributionForm\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Project.Contact.Email\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Project.Contact.Email\" FieldValue=\"marmora@letras.ufrj.br\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"DocumentLanguages.Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.DocumentLanguages.Description\" FieldValue=\"The language ids listed below are set as description languages in subbranches and sessions of this corpus.\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Title\" FieldValue=\"Brazil\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"ContentType\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.ContentType\" FieldValue=\"Discourse\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Access.Availability\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Access.Availability\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Publisher\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Publisher\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Keys.Key.CorpusImdiLink\">"
        + "<FieldData KeyName=\"CorpusImdiLink\" Path=\".METATRANSCRIPT.Catalogue.Keys.Key\" FieldValue=\"http://corpus1.mpi.nl/qfs1/media-archive/silang_data/Corpusstructure/1-02-09.imdi\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Project.Id\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Project.Id\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Project.Contact.Organisation\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Project.Contact.Organisation\" FieldValue=\"Max Planck Institute for Psycholinguistics\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Project.Contact.Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Project.Contact.Name\" FieldValue=\"Sergio Marmora de Andrade\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Format.Text\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Format.Text\" FieldValue=\"x-eaf+xml\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Keys.Key.CorpusTreePath\">"
        + "<FieldData KeyName=\"CorpusTreePath\" Path=\".METATRANSCRIPT.Catalogue.Keys.Key(4)\" FieldValue=\"MPI corpora: Sign Language Typology: urban sign languages: Brazil\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Author\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Author\" FieldValue=\"Sergio Marmora de Andrade\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Project.Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Project.Name\" FieldValue=\"SLTypology-urban-Brazil\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Date\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Date\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Format.Video\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Format.Video\" FieldValue=\"video/x-mpeg1, video/x-mpeg2\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Format.Image\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Format.Image\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Pricing\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Pricing\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Project.Contact.Address\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Project.Contact.Address\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Access.Date\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Access.Date\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Access.Contact\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.Access.Contact\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Keys.Key.CorpusBrowserLink\">"
        + "<FieldData KeyName=\"CorpusBrowserLink\" Path=\".METATRANSCRIPT.Catalogue.Keys.Key(2)\" FieldValue=\"http://corpus1.mpi.nl/ds/imdi_browser/?openpath=MPI77430%23\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"ContactPerson\">"
        + "<FieldData Path=\".METATRANSCRIPT.Catalogue.ContactPerson\" FieldValue=\"Sergio Marmora de Andrade\"/>"
        + "</FieldGroup>"
        + "</DataNode>",
        "<DataNode Label=\"Texts\" ID=\"hdl:1839/00-0000-0000-0001-2E77-E\">"
        + "<FieldGroup Label=\"Name\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Name\" FieldValue=\"Texts\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Title\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Title\" FieldValue=\"Texts\"/>"
        + "</FieldGroup>"
        + "<FieldGroup Label=\"Description\">"
        + "<FieldData Path=\".METATRANSCRIPT.Corpus.Description\" FieldValue=\"\"/>"
        + "</FieldGroup>"
        + "</DataNode>"};
}
